<?php
/**
 * GET /api/system/backup.php
 * Generates and downloads a complete SQL database dump for backup and recovery
 */

declare(strict_types=1);

require_once __DIR__ . '/../../config/cors.php';
require_once __DIR__ . '/../../config/database.php';
require_once __DIR__ . '/../../helpers/response.php';
require_once __DIR__ . '/../../helpers/logger.php';
require_once __DIR__ . '/../../middleware/auth.php';

sendCorsHeaders();

if ($_SERVER['REQUEST_METHOD'] !== 'GET' && $_SERVER['REQUEST_METHOD'] !== 'POST') {
    sendApiResponse(false, "Method Not Allowed", null, 405);
}

try {
    $db = (new Database())->getConnection();
    $currentUser = requireAuth($db);

    // Only super_admin or admin can trigger database backups
    if (!in_array($currentUser['role'], ['super_admin', 'admin'])) {
        sendApiResponse(false, "Forbidden: Only Administrators can create database backups", null, 403);
    }

    $download = isset($_GET['download']) && $_GET['download'] === 'true';

    // List of core tables to backup
    $tables = [
        'users',
        'categories',
        'tags',
        'media',
        'posts',
        'post_tags',
        'post_revisions',
        'audit_logs'
    ];

    $sqlDump = "-- ==============================================================================\n";
    $sqlDump .= "-- DATABASE SQL BACKUP DUMP\n";
    $sqlDump .= "-- Generated By: " . addslashes($currentUser['name']) . " (" . $currentUser['email'] . ")\n";
    $sqlDump .= "-- Date: " . date('Y-m-d H:i:s T') . "\n";
    $sqlDump .= "-- ==============================================================================\n\n";
    $sqlDump .= "SET FOREIGN_KEY_CHECKS = 0;\n\n";

    foreach ($tables as $table) {
        // Get Create Table syntax
        try {
            $createTableStmt = $db->query("SHOW CREATE TABLE `{$table}`");
            $row = $createTableStmt->fetch(PDO::FETCH_ASSOC);
            if (!empty($row['Create Table'])) {
                $sqlDump .= "DROP TABLE IF EXISTS `{$table}`;\n";
                $sqlDump .= $row['Create Table'] . ";\n\n";
            }

            // Get Rows data
            $rowsStmt = $db->query("SELECT * FROM `{$table}`");
            $rows = $rowsStmt->fetchAll(PDO::FETCH_ASSOC);

            if (!empty($rows)) {
                $columns = array_keys($rows[0]);
                $escapedCols = array_map(fn($col) => "`{$col}`", $columns);
                $colsSql = implode(', ', $escapedCols);

                $sqlDump .= "INSERT INTO `{$table}` ({$colsSql}) VALUES\n";

                $valueRows = [];
                foreach ($rows as $row) {
                    $escapedVals = [];
                    foreach ($row as $val) {
                        if ($val === null) {
                            $escapedVals[] = "NULL";
                        } else if (is_numeric($val)) {
                            $escapedVals[] = $val;
                        } else {
                            $escapedVals[] = "'" . addslashes((string)$val) . "'";
                        }
                    }
                    $valueRows[] = "(" . implode(', ', $escapedVals) . ")";
                }

                $sqlDump .= implode(",\n", $valueRows) . ";\n\n";
            }
        } catch (Exception $tableEx) {
            $sqlDump .= "-- Skipping table '{$table}': " . $tableEx->getMessage() . "\n\n";
        }
    }

    $sqlDump .= "SET FOREIGN_KEY_CHECKS = 1;\n";
    $sqlDump .= "-- END OF BACKUP\n";

    // Log audit action
    LoggerHelper::logAudit($db, $currentUser['id'], 'DATABASE_BACKUP', 'SYSTEM', null, ['filename' => "backup_" . date('Y-m-d_H-i') . ".sql"]);

    if ($download) {
        $filename = "blog_cms_dump_" . date('Y-m-d_His') . ".sql";
        header('Content-Type: application/sql');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Content-Length: ' . strlen($sqlDump));
        echo $sqlDump;
        exit();
    }

    sendApiResponse(true, "Database SQL backup generated successfully", [
        'timestamp' => date('Y-m-d H:i:s'),
        'file_name' => "blog_cms_dump_" . date('Y-m-d') . ".sql",
        'size_bytes' => strlen($sqlDump),
        'sql_dump' => $sqlDump
    ]);

} catch (Exception $e) {
    sendApiResponse(false, "Failed to generate database backup: " . $e->getMessage(), null, 500);
}
